### ISSUE TITLE
BUG: Unphysical estimated for volumes in the mpmorph workflow

### ISSUE THREAD

**Issue by abhijeetgangan** [materialsproject/atomate2#1046]
The `get_average_volume_from_mp` method returns unphysical volume guesses for some combinations. 

Example - `["Ho__Te__Tl", false, 403.6222099183899, 5, "mp"]` 

This results in volume being much larger and can be traced to the [mp structure](https://next-gen.materialsproject.org/materials/mp-1213656?chemsys=Ho-Te-Tl). 

There are many such examples which include common elements like `Fe__Ti__V`.

There should either be a bounds check or a filter to remove bad structures. A good default would be to use covalent radii or Vegard's law to estimate the volume.

**Comment by orionarcher** [comment]
Tagging at @BryantLi-BLI and @esoteric-ephemera here. As a little more context, this results in very unphysical densities for a small subset of compositions, see below. The underlying issue is the unphysical structures coming from mp.

![image](https://github.com/user-attachments/assets/20cad50d-0c0c-4204-9b46-fdb2c626dbb9)

**Comment by esoteric-ephemera** [comment]
Good to know. While it's not great in practice, I don't know that it's a bug (everything is working as intended, just the underlying data isn't accurate)

You might want to see if you get a more realistic estimate using the ICSD data. If not, you can manually provide a volume estimate from an arbitrary method by specifying a numeric value for `vol_per_atom_source` in `atomate2.common.jobs.mpmorph.get_random_packed_structure`

FWIW, we apply something like Vegard's law when a composition doesn't exist in either MP or ICSD

**Comment by BryantLi-BLI** [comment]
To add onto what @esoteric-ephemera is saying: I also don't believe that this is a bug. I think this is just a limit of what we currently have based on the information stored on MP/ICSD for volume per atoms. 

From a practical standpoint, if you just need to obtain working structures, it may also be helpful to tune up `vol_mul` variable when using the gen_random_packed_structure function. This should be possible to use MPMorph on said high density structures, but just decrease the density before hand by making `vol_mul=1.2` for example. This should still allow for the workflow to relax the structures into a lower energy state.

If the issue is after you perform the mpmorph workflow and these are the structures are the product of the production runs, it's likely that those particular amorphous structures do not obey the EOS fit rule in itself, and that will lead to a much longer discussion.

**Comment by abhijeetgangan** [comment]
Thank you for your feedback. I am closing this issue since it is not a bug and we found that using Vegard's law gave us more are less the same densities without the edge cases from mp.

<img width="682" alt="Screenshot 2024-11-10 at 3 59 44 PM" src="https://github.com/user-attachments/assets/eb2fd7b1-0e67-4a2a-b93c-c42da2462f70">
