### ISSUE TITLE
BUG: Additional input args are added to the INCAR from Vasprun

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#16]
**Describe the bug**
Due to the logic shown [here](https://github.com/materialsproject/atomate2/blob/main/src/atomate2/vasp/sets/base.py#L487) in the `VaspInputSetGenerator`, the INCAR flags that get carried over to a child calculation are taken from the `vasprun.xml` file. However, this can lead to very confusing behavior. For instance, in the attached files, I never used `LMAXTAU` or `KPOINT_BSE` in my `config_dict` or `user_incar_settings`, yet it appears in any child jobs. This is because, while these parameters weren't set in the INCAR, they were included in `vasprun.incar`. VASP for some reason decided to push these parameters up to the INCAR part of the `vasprun.xml` even though they were never explicitly set.

If the INCAR is available, my suggestion would be to prioritize reading that over the `vasprun.xml` and only read the latter if the INCAR has vanished. 

[INCAR.orig.txt](https://github.com/materialsproject/atomate2/files/7600975/INCAR.orig.txt)
[INCAR.txt](https://github.com/materialsproject/atomate2/files/7600976/INCAR.txt)
[vasprun.xml.txt](https://github.com/materialsproject/atomate2/files/7600977/vasprun.xml.txt)

**Comment by utf** [comment]
Hi @arosen93. This idea of carrying over settings from the previous INCAR was taken over from atomate1 but I see that this gives unexpected results.

A couple of points:
- This appears to be fixed in VASP 6+ as I can't reproduce this behaviour (my vaspruns don't contain `KPOINT_BSE` for example).
- I think preferentially using the INCAR makes sense and would be easy enough to implement but I'm not sure it is a major issue, as VASP appears to be promoting the default for these values.

If you'd like to fix, then it should be as simple as adjusting the line you linked to.

**Comment by arosen93** [comment]
Ah, I see! I think it's fixed in VASP 6+ as well. I'll close this then -- no need to fix what's not broken :)
