### ISSUE TITLE
Improvement of preconvergence step lobster workflow

### ISSUE THREAD

**Issue by JaGeo** [materialsproject/atomate2#275]
@utf , there is still one other issue with the Lobster workflow. I have implemented this pre-convergence step of the WAVECAR. I have, however, the feeling that the speed-up is extremely small. I am not sure why this is the case. VASP still needs many electronic steps after starting from such a pre-converged WAVECAR. I might need to do some more tests to make this really efficient or test some larger structures.

**Comment by utf** [comment]
I have a couple of thoughts having looked more closely at the lobster workflow:
1. I wonder if the need for many more steps is because NBANDS is only set after the preconvergence job? If you could do the pre-convergence with the same higher NBANDS that might make things faster since it would have converged all necessary bands?
2. Can you use a non-scf uniform input set for the `LobsterStaticMaker`? Obviously this won't work for hybrid calculations but that should allow you to go to very dense k-point meshes without much slowdown. If we did this, we should make the preconvergence step compulsory. In fact, an even better approach would be to replace both the `preconverge_static_maker` and `lobster_static_maker` with a single maker `lobster_uniform_maker` that is actually a flow maker. E.g., some variation of `UniformBandStructureMaker` but with symmetry disabled for the second job.
3. Can we switch to using `reciprocal_density` instead of `grid_density` for the `LobsterStaticMaker`?

**Comment by JaGeo** [comment]
1. Yes, this is also my assumption. I have to test it in detail for some cases once our cluster is back up.
2. I haven't performed Lobster computations in this way. This would also be something we need to check.
3. Sure. I think it is much better

**Comment by JaGeo** [comment]
Strategy 2 seems to work now:

51 s with smaller number of reciprocal points (reciprocal_density: 100) and without symmetry (50s), uniform band structure computation with wavecar writing (reciprocal_density: 400, 150 s)

400 s with only one static computation (400 s, reciproal_density: 400)

I will now try to confirm that the Lobster outputs also still look fine based on this.

**Comment by JaGeo** [comment]
![image](https://user-images.githubusercontent.com/22094846/226878604-2fa1fae5-3b24-4a95-b505-90db376676c7.png)
It looks very similar. Just VASP sets the band gap differently in VASP 6 and in this new maker ISPIN is set to 1 in this case.

I also compared ICOHPLIST.lobster and again the agreement is very good.

**Comment by utf** [comment]
Nice! That looks promising. 

By the way, I think if you upgrade to the latest VASP, they fixed the issue with setting the Fermi level so it goes back to how it used to be.

**Comment by JaGeo** [comment]
That's great. I guess we will then compile a new version soon!

**Comment by JaGeo** [comment]
I will now create new test data and fix the tests and also check if all folders in the output schema have been included.

**Comment by JaGeo** [comment]
I will close it as the mentioned pull request has been merged.
