### ISSUE TITLE
Minting a new Atomate2 version

### ISSUE THREAD

**Issue by arosen93** [materialsproject/atomate2#467]
This issue is meant to track tasks that need to be completed for the next atomate2 version to be released. This will obviously depend a lot on @utf's comments, but here are some that I'm aware of:

- We need to provide a detailed changelog of all PRs since the last release. This might be something we want to crowdsource at the next atomate2 meeting. Alternatively, I am willing to take a day to go through them since I'm somewhat invested in a new release 😉 
- We should merge #362 since it is close to completion and is important.
- We should probably get #412 merged since that's an important bug fix.

**Comment by JaGeo** [comment]
I would be happy if the fixes to the phonons workflow would get included. They would both fix issues/bugs (#276 and #398).

**Comment by arosen93** [comment]
Thanks! There were discussions at the last atomate2 meeting about adding new maintainers, so we can make sure these things get taken care of too.

**Comment by JaGeo** [comment]
This sounds great. Happy to hear about such plans since we plan to contribute more work in the future as well.

**Comment by utf** [comment]
Agreed we should focus on getting a new version out. Some help I can use GitHub to generate release notes, the current release notes are pasted below. Some help tidying them later would be helpful.

In terms of PRs to merge before releasing a new version. Definitely:
- https://github.com/materialsproject/atomate2/pull/362
- https://github.com/materialsproject/atomate2/pull/412
- https://github.com/materialsproject/emmet/pull/764 (I think this is waiting on a PR in emmet @mjwen, @munrojm)

And potentially:
- https://github.com/materialsproject/atomate2/pull/276

## What's Changed
* Bump jobflow from 0.1.9 to 0.1.10 by @dependabot in https://github.com/materialsproject/atomate2/pull/263
* Bump pymatgen from 2023.2.28 to 2023.3.10 by @dependabot in https://github.com/materialsproject/atomate2/pull/264
* Bump pydantic from 1.10.5 to 1.10.6 by @dependabot in https://github.com/materialsproject/atomate2/pull/262
* Bump custodian from 2022.5.26 to 2023.3.10 by @dependabot in https://github.com/materialsproject/atomate2/pull/265
* Fix Lobster Schema by @JaGeo in https://github.com/materialsproject/atomate2/pull/266
* CP2K Support by @nwinner in https://github.com/materialsproject/atomate2/pull/157
* Bump jupyter-book from 0.14.0 to 0.15.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/261
* Add more documentation for Lobster by @JaGeo in https://github.com/materialsproject/atomate2/pull/267
* Extension of Lobster schema and additional tests by @JaGeo in https://github.com/materialsproject/atomate2/pull/272
* Use emmet VASP task document by @utf in https://github.com/materialsproject/atomate2/pull/269
* VASP inputset updates by @utf in https://github.com/materialsproject/atomate2/pull/270
* Linting by @utf in https://github.com/materialsproject/atomate2/pull/274
* Improve Lobster workflow preconverge step, kpoints, docs by @JaGeo in https://github.com/materialsproject/atomate2/pull/277
* fix lso dos of lobster being not saved in schema by @naik-aakash in https://github.com/materialsproject/atomate2/pull/279
* Bump pydantic from 1.10.6 to 1.10.7 by @dependabot in https://github.com/materialsproject/atomate2/pull/284
* Bump pymatgen-analysis-defects from 2023.3.3 to 2023.3.25 by @dependabot in https://github.com/materialsproject/atomate2/pull/285
* Bump pymatgen from 2023.3.10 to 2023.3.23 by @dependabot in https://github.com/materialsproject/atomate2/pull/281
* add has_doscar_lso field to Lobsterout schema model and update lobsterpy version by @naik-aakash in https://github.com/materialsproject/atomate2/pull/286
* Bump emmet-core from 0.51.0 to 0.51.6 by @dependabot in https://github.com/materialsproject/atomate2/pull/288
* fix _get_strong_bonds function by @naik-aakash in https://github.com/materialsproject/atomate2/pull/289
* [Bug Fix] For stringing defect calculations together by @jmmshn in https://github.com/materialsproject/atomate2/pull/292
* Bump ipython from 8.11.0 to 8.12.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/294
* Bump phonopy from 2.17.2 to 2.18.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/295
* BUGFIX `auto_lreal` by @jmmshn in https://github.com/materialsproject/atomate2/pull/297
* Bump pymatgen-analysis-defects from 2023.3.25 to 2023.4.5 by @dependabot in https://github.com/materialsproject/atomate2/pull/305
* Bump pytest from 7.2.2 to 7.3.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/307
* Bump pytest from 7.3.0 to 7.3.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/310
* Bump monty from 2022.9.9 to 2023.4.10 by @dependabot in https://github.com/materialsproject/atomate2/pull/312
* Bump ipython from 8.12.0 to 8.13.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/316
* Bump emmet-core from 0.51.6 to 0.52.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/318
* Fix `Yb` PSP: change `Yb_2` to `Yb_3` by @janosh in https://github.com/materialsproject/atomate2/pull/319
* added simple chg check by @jmmshn in https://github.com/materialsproject/atomate2/pull/320
* Switch to emmet's `MoleculeMetadata` by @arosen93 in https://github.com/materialsproject/atomate2/pull/301
* Fix typo by @janosh in https://github.com/materialsproject/atomate2/pull/321
* Bump custodian from 2023.3.10 to 2023.5.7 by @dependabot in https://github.com/materialsproject/atomate2/pull/324
* Bump ipython from 8.13.1 to 8.13.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/325
* Update update-precommit.yml by @utf in https://github.com/materialsproject/atomate2/pull/330
* Auto-update pre-commit hooks by @github-actions in https://github.com/materialsproject/atomate2/pull/332
* Update dependencies by @utf in https://github.com/materialsproject/atomate2/pull/329
* Use furo for docs theme by @utf in https://github.com/materialsproject/atomate2/pull/331
* Bump phonopy from 2.18.0 to 2.19.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/337
* Bump pymatgen from 2023.3.23 to 2023.5.10 by @dependabot in https://github.com/materialsproject/atomate2/pull/336
* Bump custodian from 2023.5.7 to 2023.5.12 by @dependabot in https://github.com/materialsproject/atomate2/pull/338
* Bump mp-api from 0.33.1 to 0.33.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/340
* Bump emmet-core from 0.54.3 to 0.55.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/341
* Bump pymatgen-analysis-defects from 2023.04.05 to 2023.5.8 by @dependabot in https://github.com/materialsproject/atomate2/pull/339
* Bump seekpath from 2.0.1 to 2.1.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/346
* Bump emmet-core from 0.55.0 to 0.55.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/350
* Bump mp-api from 0.33.2 to 0.33.3 by @dependabot in https://github.com/materialsproject/atomate2/pull/349
* Bump dscribe from 1.2.2 to 2.0.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/347
* Bump phonopy from 2.19.0 to 2.19.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/351
* Add missing molecule field to cclib TaskDocument by @arosen93 in https://github.com/materialsproject/atomate2/pull/353
* More `ruff` by @janosh in https://github.com/materialsproject/atomate2/pull/344
* Bump furo from 2023.03.27 to 2023.5.20 by @dependabot in https://github.com/materialsproject/atomate2/pull/348
* Add forcefield schemas/makers to atomate2 by @matthewkuner in https://github.com/materialsproject/atomate2/pull/322
* Auto-update pre-commit hooks by @github-actions in https://github.com/materialsproject/atomate2/pull/335
* Move all type-hint only imports behind `if TYPE_CHECKING` by @janosh in https://github.com/materialsproject/atomate2/pull/354
* Bump pytest-cov from 4.0.0 to 4.1.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/357
* Bump pydantic from 1.10.7 to 1.10.8 by @dependabot in https://github.com/materialsproject/atomate2/pull/358
* Bump typing-extensions from 4.5.0 to 4.6.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/359
* Bump typing-extensions from 4.6.2 to 4.6.3 by @dependabot in https://github.com/materialsproject/atomate2/pull/366
* Bump ipython from 8.13.2 to 8.14.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/367
* Bump pymatgen from 2023.5.10 to 2023.5.31 by @dependabot in https://github.com/materialsproject/atomate2/pull/368
* Bump pymatgen-analysis-defects from 2023.5.8 to 2023.6.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/369
* Update Lobster documentation by @JaGeo in https://github.com/materialsproject/atomate2/pull/376
* Bump emmet-core from 0.55.2 to 0.55.4 by @dependabot in https://github.com/materialsproject/atomate2/pull/377
* Fix docs typos by @janosh in https://github.com/materialsproject/atomate2/pull/373
* Fix overriding `magmoms` in `update_user_incar_settings()` by @janosh in https://github.com/materialsproject/atomate2/pull/375
* Update FireWorks section of docs by @arosen93 in https://github.com/materialsproject/atomate2/pull/378
* Add a copy button to code blocks by @arosen93 in https://github.com/materialsproject/atomate2/pull/382
* Bump pydantic from 1.10.8 to 1.10.9 by @dependabot in https://github.com/materialsproject/atomate2/pull/386
* Bump pytest from 7.3.1 to 7.3.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/388
* Bump emmet-core from 0.55.4 to 0.55.5 by @dependabot in https://github.com/materialsproject/atomate2/pull/385
* allow elastically unstable structures by @matthewkuner in https://github.com/materialsproject/atomate2/pull/355
* Auto-update pre-commit hooks by @github-actions in https://github.com/materialsproject/atomate2/pull/390
* Add `m3gnet` support to Atomate2 by @matthewkuner in https://github.com/materialsproject/atomate2/pull/380
* Bump myst-parser from 1.0.0 to 2.0.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/393
* Bump emmet-core from 0.55.5 to 0.57.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/392
* Bump custodian from 2023.5.12 to 2023.6.5 by @dependabot in https://github.com/materialsproject/atomate2/pull/387
* clean up doc, remove left-overs from amset example by @JaGeo in https://github.com/materialsproject/atomate2/pull/394
* `ruff` select `perflint` `flake8-slots` by @janosh in https://github.com/materialsproject/atomate2/pull/395
* Bump pytest from 7.3.2 to 7.4.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/403
* Fix encoding of input `Molecule` coordinates in cclib `TaskDocument` by @arosen93 in https://github.com/materialsproject/atomate2/pull/411
* Auto-update pre-commit hooks by @github-actions in https://github.com/materialsproject/atomate2/pull/410
* Bump typing-extensions from 4.6.3 to 4.7.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/419
* Bump emmet-core from 0.57.1 to 0.58.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/417
* Bump phonopy from 2.19.1 to 2.20.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/416
* Bump matgl from 0.5.6 to 0.7.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/401
* Bump chgnet from 0.1.3 to 0.1.4 by @dependabot in https://github.com/materialsproject/atomate2/pull/399
* Bump `ruff` and fix `PERF401`: Use a list comprehension to create transformed list by @janosh in https://github.com/materialsproject/atomate2/pull/421
* Bump emmet-core from 0.58.0 to 0.58.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/427
* Bump click from 8.1.3 to 8.1.4 by @dependabot in https://github.com/materialsproject/atomate2/pull/425
* Bump autodoc-pydantic from 1.8.0 to 1.9.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/426
* Simplify: `dict.get(key, None)` -> `dict.get(key)` by @janosh in https://github.com/materialsproject/atomate2/pull/429
* Bump click from 8.1.4 to 8.1.5 by @dependabot in https://github.com/materialsproject/atomate2/pull/435
* Bump emmet-core from 0.58.2 to 0.60.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/437
* Bump matgl from 0.7.0 to 0.7.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/438
* Bump pymatgen-analysis-defects from 2023.6.1 to 2023.7.12 by @dependabot in https://github.com/materialsproject/atomate2/pull/439
* More details for lobster documentation by @JaGeo in https://github.com/materialsproject/atomate2/pull/431
* update lobstertask schema: add bandoverlaps,grosspop and sitepotentials fields by @naik-aakash in https://github.com/materialsproject/atomate2/pull/404
* Bump dscribe from 2.0.0 to 2.0.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/448
* Bump chgnet from 0.1.4 to 0.2.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/444
* Bump custodian from 2023.6.5 to 2023.7.22 by @dependabot in https://github.com/materialsproject/atomate2/pull/446
* Bump pyyaml from 6.0 to 6.0.1 by @dependabot in https://github.com/materialsproject/atomate2/pull/449
* Bump click from 8.1.5 to 8.1.6 by @dependabot in https://github.com/materialsproject/atomate2/pull/447
* Deploy docs on every commit to `main` by @janosh in https://github.com/materialsproject/atomate2/pull/422
* Add clearer documentation on lobster worker by @JaGeo in https://github.com/materialsproject/atomate2/pull/440
* `dict.setdefault` instead of `if key not in dict: dict[key] = ...` by @janosh in https://github.com/materialsproject/atomate2/pull/452
* Bump pymatgen-analysis-defects from 2023.7.12 to 2023.7.24 by @dependabot in https://github.com/materialsproject/atomate2/pull/457
* Bump sphinx-design from 0.4.1 to 0.5.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/456
* Bump furo from 2023.5.20 to 2023.7.26 by @dependabot in https://github.com/materialsproject/atomate2/pull/459
* Bump pymatgen-analysis-defects from 2023.7.24 to 2023.7.31 by @dependabot in https://github.com/materialsproject/atomate2/pull/463
* Bump matgl from 0.7.1 to 0.8.0 by @dependabot in https://github.com/materialsproject/atomate2/pull/462
* Bump matgl from 0.8.0 to 0.8.2 by @dependabot in https://github.com/materialsproject/atomate2/pull/470
* Update CondensedBondingAnalysis schema by @naik-aakash in https://github.com/materialsproject/atomate2/pull/469
* [FIX] fix elastic tensor flow  by @mjwen in https://github.com/materialsproject/atomate2/pull/415
* [BUG FIX] Edge case for Magmoms by @jmmshn in https://github.com/materialsproject/atomate2/pull/460
* Bump monty from 2023.5.8 to 2023.8.8 by @dependabot in https://github.com/materialsproject/atomate2/pull/474

## New Contributors
* @naik-aakash made their first contribution in https://github.com/materialsproject/atomate2/pull/279
* @matthewkuner made their first contribution in https://github.com/materialsproject/atomate2/pull/322

**Full Changelog**: https://github.com/materialsproject/atomate2/compare/v0.0.10...v0.0.11

**Comment by janosh** [comment]
I'd exclude `dependabot` from release notes.

**Comment by computron** [comment]
Do release notes take time to prepare? If so, do we *really* need them?

**Comment by janosh** [comment]
@computron GitHub auto-generates these for you. Really nice feature.

**Comment by JaGeo** [comment]
General note: release notes are very helpful to showcase contributions to code before a publication in a journal. Luckily, this github feature exists

**Comment by utf** [comment]
Thanks for the tip about `.github/release.yml`. I've added some more stuff in there, and now the automatically generated release notes use the tags to create sections. The current release notes look like this:



## What's Changed
### New Features 🎉
* CP2K Support by @nwinner in https://github.com/materialsproject/atomate2/pull/157
* Add forcefield schemas/makers to atomate2 by @matthewkuner in https://github.com/materialsproject/atomate2/pull/322
* Add `m3gnet` support to Atomate2 by @matthewkuner in https://github.com/materialsproject/atomate2/pull/380
* Phonons for forcefields by @JaGeo in https://github.com/materialsproject/atomate2/pull/398
### Bug Fixes 🐛
* Fix Lobster Schema by @JaGeo in https://github.com/materialsproject/atomate2/pull/266
* fix lso dos of lobster being not saved in schema by @naik-aakash in https://github.com/materialsproject/atomate2/pull/279
* fix _get_strong_bonds function by @naik-aakash in https://github.com/materialsproject/atomate2/pull/289
* [Bug Fix] For stringing defect calculations together by @jmmshn in https://github.com/materialsproject/atomate2/pull/292
* BUGFIX `auto_lreal` by @jmmshn in https://github.com/materialsproject/atomate2/pull/297
* Fix `Yb` PSP: change `Yb_2` to `Yb_3` by @janosh in https://github.com/materialsproject/atomate2/pull/319
* Fix typo by @janosh in https://github.com/materialsproject/atomate2/pull/321
* Fix overriding `magmoms` in `update_user_incar_settings()` by @janosh in https://github.com/materialsproject/atomate2/pull/375
* Fix encoding of input `Molecule` coordinates in cclib `TaskDocument` by @arosen93 in https://github.com/materialsproject/atomate2/pull/411
* [FIX] fix elastic tensor flow  by @mjwen in https://github.com/materialsproject/atomate2/pull/415
* [BUG FIX] Edge case for Magmoms by @jmmshn in https://github.com/materialsproject/atomate2/pull/460
* [FIX] Fix major bug that caused `user_incar_settings` to be overwritten in some cases by @matthewkuner in https://github.com/materialsproject/atomate2/pull/412
### Enhancements 🛠
* Extension of Lobster schema and additional tests by @JaGeo in https://github.com/materialsproject/atomate2/pull/272
* Use emmet VASP task document by @utf in https://github.com/materialsproject/atomate2/pull/269
* VASP inputset updates by @utf in https://github.com/materialsproject/atomate2/pull/270
* Linting by @utf in https://github.com/materialsproject/atomate2/pull/274
* Improve Lobster workflow preconverge step, kpoints, docs by @JaGeo in https://github.com/materialsproject/atomate2/pull/277
* add has_doscar_lso field to Lobsterout schema model and update lobsterpy version by @naik-aakash in https://github.com/materialsproject/atomate2/pull/286
* added simple chg check by @jmmshn in https://github.com/materialsproject/atomate2/pull/320
* Switch to emmet's `MoleculeMetadata` by @arosen93 in https://github.com/materialsproject/atomate2/pull/301
* Update update-precommit.yml by @utf in https://github.com/materialsproject/atomate2/pull/330
* Update dependencies by @utf in https://github.com/materialsproject/atomate2/pull/329
* Add missing molecule field to cclib TaskDocument by @arosen93 in https://github.com/materialsproject/atomate2/pull/353
* allow elastically unstable structures by @matthewkuner in https://github.com/materialsproject/atomate2/pull/355
* update lobstertask schema: add bandoverlaps,grosspop and sitepotentials fields by @naik-aakash in https://github.com/materialsproject/atomate2/pull/404
* Update CondensedBondingAnalysis schema by @naik-aakash in https://github.com/materialsproject/atomate2/pull/469
* Phonon tweaks by @utf in https://github.com/materialsproject/atomate2/pull/276
* Update to Defects WF by @jmmshn in https://github.com/materialsproject/atomate2/pull/430
* Small change to `gunzip` to allow better restarting by @jmmshn in https://github.com/materialsproject/atomate2/pull/476
* Remove VASP calc types schema  by @mjwen in https://github.com/materialsproject/atomate2/pull/407
* Optionally zip files at the end of jobs by @gpetretto in https://github.com/materialsproject/atomate2/pull/414
### Documentation 📖
* Add more documentation for Lobster by @JaGeo in https://github.com/materialsproject/atomate2/pull/267
* Use furo for docs theme by @utf in https://github.com/materialsproject/atomate2/pull/331
* Update Lobster documentation by @JaGeo in https://github.com/materialsproject/atomate2/pull/376
* Fix docs typos by @janosh in https://github.com/materialsproject/atomate2/pull/373
* Update FireWorks section of docs by @arosen93 in https://github.com/materialsproject/atomate2/pull/378
* Add a copy button to code blocks by @arosen93 in https://github.com/materialsproject/atomate2/pull/382
* clean up doc, remove left-overs from amset example by @JaGeo in https://github.com/materialsproject/atomate2/pull/394
* More details for lobster documentation by @JaGeo in https://github.com/materialsproject/atomate2/pull/431
* Deploy docs on every commit to `main` by @janosh in https://github.com/materialsproject/atomate2/pull/422
* Add clearer documentation on lobster worker by @JaGeo in https://github.com/materialsproject/atomate2/pull/440
* Docs: add basic workflow tutorial by @rkingsbury in https://github.com/materialsproject/atomate2/pull/408
* Use GitHub's `deploy-pages` action to deploy docs by @janosh in https://github.com/materialsproject/atomate2/pull/475
### House-Keeping 🧹
* More `ruff` by @janosh in https://github.com/materialsproject/atomate2/pull/344
* Move all type-hint only imports behind `if TYPE_CHECKING` by @janosh in https://github.com/materialsproject/atomate2/pull/354
* `ruff` select `perflint` `flake8-slots` by @janosh in https://github.com/materialsproject/atomate2/pull/395
* Bump `ruff` and fix `PERF401`: Use a list comprehension to create transformed list by @janosh in https://github.com/materialsproject/atomate2/pull/421
* Simplify: `dict.get(key, None)` -> `dict.get(key)` by @janosh in https://github.com/materialsproject/atomate2/pull/429
* `dict.setdefault` instead of `if key not in dict: dict[key] = ...` by @janosh in https://github.com/materialsproject/atomate2/pull/452

## New Contributors
* @naik-aakash made their first contribution in https://github.com/materialsproject/atomate2/pull/279
* @matthewkuner made their first contribution in https://github.com/materialsproject/atomate2/pull/322
* @gpetretto made their first contribution in https://github.com/materialsproject/atomate2/pull/414

**Full Changelog**: https://github.com/materialsproject/atomate2/compare/v0.0.10...v0.0.11

**Comment by utf** [comment]
I've released a new version. We can also push a new one once the MP workflows are added.
