### ISSUE TITLE
Database and data storage 

### ISSUE THREAD

**Issue by Zhuoying** [materialsproject/atomate2#478]
This issue is open for discussions on the database/data storage-related things with @utf and more new developers/contributors  involved.

1. Generally, atomate2 uses two database collections (small `docs` and large `data`) to store data. GridFS in MongoDB does not need future configurations from the user's side. But for developers who want to contribute new workflows, are there any general rules to organize the results (`outputs`) and keep their database collections consistent with existing `Flow` data storage?  @hrushikesh-s Please comment with the detailed question you met when converting wf from atomate to atomate2. Also, some `store` formatting I thought in atomate2, might actually be in `Jobflow` (`JobStore`). I believe @utf might have some schemes/thoughts under this (where things should be put in, atomate2 or jobflow) to share with new developers?

2. A question from @arosen93 (correct me if I remember wrongly): Is any other database server other than MongoDB supported by atomate2? I found in atomate2 documentation website (https://materialsproject.github.io/atomate2/user/install.html#advanced_storage) it mentions other storage types available (such as Amazon S3), although I did not see a valid page for `advanced_storage`. @utf any comments or suggestions?
<img width="837" alt="Screenshot 2023-08-16 at 5 07 41 PM" src="https://github.com/materialsproject/atomate2/assets/10410019/790c379e-65f4-4211-b3fe-03b8fdfc55cf">

I think currently, many MP colleagues are actively migrating their workflows to or creating a new version in atomate2. So here might be a place or initial thread to discuss the database issue. Your issues on this topic are welcome to post here.

**Comment by arosen93** [comment]
> A question from @arosen93 (correct me if I remember wrongly): anything database server other than MongoDB supported by atomate2? I found in atomate2 documentation website (https://materialsproject.github.io/atomate2/user/install.html#advanced_storage) it mentions other storage types available (such as Amazon S3), although I did not see a valid page for advanced_storage.

Since maggma is an Atomate2 dependency, Atomate2 should be able to interface with any Maggma store: https://materialsproject.github.io/maggma/reference/stores/

**Comment by Zhuoying** [comment]
@arosen93 Thanks for the list. A very good point to mention. I did not expect such many stores type supported in atomate2.

**Comment by utf** [comment]
The plan was to have just two stores (`docs` and `data`) to avoid users having to configure new collections for specific workflows. If there is a strong desire to add a new required store (e.g., perhaps everyone wants to store wavefunctions in a separate store), then we could add this in. Although I think there should be a very good reason and we should communicate this very clearly in the setup instructions, since all users will have to update their config.

> for developers who want to contribute new workflows, are there any general rules to organize the results 

Basically, anything which is potentially larger than say 5 Mb should probably go in the data store. The total size of a MongoDB document can't be more than 16 Mb, so this limit is erring on the side of caution (considering that often the size of documents can change depending on the system studied). The good news is that it's very easy to select which store objects will get put in (and can be changed later on without breaking previous calculations).

> Is any other database server other than MongoDB supported by atomate2?

Andrew already answered this, but I definitely think we should add some more documentation to jobflow about this.

**Comment by Zhuoying** [comment]
I will close this issue and let @hrushikesh-s open a new one to discuss the detailed schemas of our lattice dynamic data format.
